### ISSUE TITLE
Issues when running the demo

### ISSUE THREAD

**Issue by rachmadvwp** [nmi-lab/dcll#6]
Hi, 
I'd like to ask about the issue that I faced when running the given demo.
Following is the log:

```
(dcll) user@PC:~/Works/dcll$ samples/run_mnist_experiments.sh
Results will be saved in Paper_results_long/
Running samples/pytorch_conv3L_mnist.py with seed 0
runs/pytorch_conv3L_mnist_/Dec13_05-08-40_PC_
Sigmoid()
Conv2D Layer  (28, 28) (26, 26) 1 16 7 1 2 1
Traceback (most recent call last):
  File "/home/user/Works/dcll/samples/pytorch_conv3L_mnist.py", line 207, in <module>
    net = ConvNetwork(args, im_dims, args.batch_size, convs, target_size,
  File "/home/user/Works/dcll/samples/pytorch_conv3L_mnist.py", line 138, in __init__
    self.layer1, n = make_conv(n, convs[0])
  File "/home/user/Works/dcll/samples/pytorch_conv3L_mnist.py", line 123, in make_conv
    layer = Conv2dDCLLlayer(in_channels = inp[0], out_channels = int(conf[0] * args.netscale),
  File "/home/user/.local/lib/python3.9/site-packages/torch-1.7.1-py3.9-linux-x86_64.egg/torch/nn/modules/module.py", line 612, in to
    return self._apply(convert)
  File "/home/user/.local/lib/python3.9/site-packages/torch-1.7.1-py3.9-linux-x86_64.egg/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python3.9/site-packages/torch-1.7.1-py3.9-linux-x86_64.egg/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/user/.local/lib/python3.9/site-packages/torch-1.7.1-py3.9-linux-x86_64.egg/torch/nn/modules/module.py", line 610, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/home/user/.local/lib/python3.9/site-packages/torch-1.7.1-py3.9-linux-x86_64.egg/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
```

I do have CUDA GPU and used it frequently. 
Could you please give an idea how to solve this issue.
Thanks in advance & Best Regards.

**Comment by rachmadvwp** [comment]
I've solved this, and will close the thread.

**Comment by jackokaiser** [comment]
Hello,

Sorry for not replying earlier- there's a more recent version of the code here: https://github.com/nmi-lab/decolle-public
